spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://${HOST:localhost}/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
  kafka:
      bootstrap-servers: PLAINTEXT://${broker:localhost}:9092

app:
  kafka:
    enable: true
    userRegistration: "user-registration-topic"
    roomReservation: "room-reservation-topic"
    kafkaMessageGroupId: "reservation-group-id"
server:
  port: 8080
