spring:
  jpa:
    generate-ddl: off
  datasource:
    url: jdbc:postgresql://${HOST:localhost}/booking_db
    username: postgres
    password: postgres
    hikari:
      schema: booking_schema
  kafka:
      bootstrap-servers: PLAINTEXT://broker:9092
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true

app:
  kafka:
    enable: true
    userRegistration: "user-registration-topic"
    roomReservation: "room-reservation-topic"
    kafkaMessageGroupId: "reservation-group-id"
server:
  port: 8080
